=== BitXad/ximpleman_web/resources/xml/facturaComputarizadaPrevalorada.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- XSD ver.23/08/2021 -->
<xs:schema xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="facturaComputarizadaPrevalorada">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabecera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nitEmisor">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="9999999999999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="razonSocialEmisor">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="200"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="municipio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="25"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono" nillable="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="25"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="numeroFactura">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="9999999999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cuf">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cufd">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoSucursal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="9999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="direccion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="500"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoPuntoVenta" nillable="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="9999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fechaEmision" type="xs:dateTime"/>
                            <xs:element name="nombreRazonSocial" type="xs:string" fixed="S/N"/>
                            <xs:element name="codigoTipoDocumentoIdentidad" type="xs:integer" fixed="5"/>
                            <xs:element name="numeroDocumento" type="xs:integer" fixed="0"/>
                            <xs:element name="codigoCliente" type="xs:string" fixed="N/A"/>
                            <xs:element name="codigoMetodoPago">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="308"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="numeroTarjeta" nillable="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="9999999999999999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="montoTotal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="montoTotalSujetoIva">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoMoneda">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="154"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tipoCambio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="montoTotalMoneda">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="leyenda">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="200"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="usuario">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoDocumentoSector" type="xs:integer" fixed="23"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="detalle" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actividadEconomica">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoProductoSin">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="99999999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoProducto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="descripcion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="500"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cantidad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="unidadMedida">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="200"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precioUnitario">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="montoDescuento" nillable="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="subTotal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="17"/>
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BitXad/ximpleman_web/resources/xml/facturaComputarizadaPrevalorada626.xml
<?xml version="1.0" encoding="utf-8"?>
<facturaComputarizadaPrevalorada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="facturaComputarizadaPrevalorada.xsd">
      <cabecera>
          <nitEmisor>5152377019</nitEmisor>
          <razonSocialEmisor>PASSWORD</razonSocialEmisor>
          <municipio>CERCADO - COCHABAMBA</municipio>
          <telefono>4511518 *(591)79999097</telefono>
          <numeroFactura>553</numeroFactura>
          <cuf>1608A399D64B18406F2033066E6E20062C45EDF4FAA6351D27BD1D6D74</cuf>
          <cufd>BQXxCKlhQRkE=Nzzc0OTIzNjFEMjc=Q3x4QXZRVkpXVUJIzNURFQzJFNTdGQ</cufd>
          <codigoSucursal>0</codigoSucursal>
          <direccion>URUGUAY Nº 454, ENTRE SAN MARTIN Y 25 DE MAYO</direccion>
          <codigoPuntoVenta>1</codigoPuntoVenta>
          <fechaEmision>2022-09-20T16:53:20.789</fechaEmision>
          <nombreRazonSocial>S/N</nombreRazonSocial>
          <codigoTipoDocumentoIdentidad>5</codigoTipoDocumentoIdentidad>
          <numeroDocumento>0</numeroDocumento>
          <codigoCliente>N/A</codigoCliente>
          <codigoMetodoPago>1</codigoMetodoPago>
          <numeroTarjeta>0</numeroTarjeta>
          <montoTotal>90.00</montoTotal>
          <montoTotalSujetoIva>90</montoTotalSujetoIva>
          <codigoMoneda>1</codigoMoneda>
          <tipoCambio>1</tipoCambio>
          <montoTotalMoneda>90.00</montoTotalMoneda>
          <leyenda>Ley N° 453: Está prohibido importar, distribuir o comercializar productos expirados o prontos a expirar.</leyenda>
          <usuario>Administrador</usuario>
          <codigoDocumentoSector>23</codigoDocumentoSector>
      </cabecera>
      <detalle>
           <actividadEconomica>465000</actividadEconomica>
           <codigoProductoSin>611849</codigoProductoSin>
           <codigoProducto>0152502326</codigoProducto>
           <descripcion>WIRELESS PCI-XPRESS 150MBPS TP-LINK TL-WN781ND</descripcion>
           <cantidad>1</cantidad>
           <unidadMedida>47</unidadMedida>
           <precioUnitario>90.00</precioUnitario>
           <montoDescuento>0</montoDescuento>
           <subTotal>90.00</subTotal>
      </detalle>
</facturaComputarizadaPrevalorada>

=== BitXad/ximpleman_web/resources/xml/facturaComputarizadaPrevalorada.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<facturaComputarizadaPrevalorada xsi:noNamespaceSchemaLocation="facturaComputarizadaPrevalorada.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <cabecera>
        <nitEmisor>1003579028</nitEmisor>
        <razonSocialEmisor>PRUEBA</razonSocialEmisor>
        <municipio>LA PAZ - BOLIVIA</municipio>
        <telefono>60117860</telefono>
        <numeroFactura>1</numeroFactura>
        <cuf>44AAEC00DBD34C53C3E42C6EE4251B5145129506A367A75AC82F24C74</cuf>
        <cufd>BQUE+QytqQUDBKVUFOSVRPQkxVRFZNVFVJBMDAwMDAwM</cufd>
        <codigoSucursal>0</codigoSucursal>
        <direccion>AV. JORGE LOPEZ #123</direccion>
        <codigoPuntoVenta>0</codigoPuntoVenta>
        <fechaEmision>2021-10-06T16:03:49.100</fechaEmision>
        <nombreRazonSocial>S/N</nombreRazonSocial>
        <codigoTipoDocumentoIdentidad>5</codigoTipoDocumentoIdentidad>
        <numeroDocumento>0</numeroDocumento>
        <codigoCliente>N/A</codigoCliente>
        <codigoMetodoPago>1</codigoMetodoPago>
        <numeroTarjeta/>
        <montoTotal>100</montoTotal>
        <montoTotalSujetoIva>100</montoTotalSujetoIva>
        <codigoMoneda>1</codigoMoneda>
        <tipoCambio>1</tipoCambio>
        <montoTotalMoneda>100</montoTotalMoneda>
        <leyenda>Ley N° 453: Tienes derecho a recibir información sobre las características y contenidos de los servicios que utilices.</leyenda>
        <usuario>pperez</usuario>
        <codigoDocumentoSector>23</codigoDocumentoSector>
    </cabecera>
</facturaComputarizadaPrevalorada>
